# Generated by Django 2.2.4 on 2019-08-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('channel', models.CharField(max_length=50)),
                ('country', models.CharField(default=None, max_length=20)),
                ('os', models.CharField(default=None, max_length=20)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('installs', models.IntegerField(default=0)),
                ('spend', models.FloatField(default=0.0)),
                ('revenue', models.FloatField(default=0.0)),
            ],
        ),
    ]
