# Generated by Django 2.2.4 on 2019-08-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemetric',
            name='channel',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
